import NextTopLoader from 'nextjs-toploader';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import '@/styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader color="#3B81F6" />
        <Header />
        <div className="mx-auto max-w-7xl py-8 md:py-20 px-4 sm:px-6">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
